### ISSUE TITLE
[Bug] Can't set falsy value with hook

### ISSUE THREAD

**Issue by pnthach95** [ammarahm-ed/react-native-mmkv-storage#163]
**Describe the bug**
Can't set falsy value (false, empty string, number 0) with hook

**To Reproduce**
1. Clone my test case: https://github.com/pnthach95/mmkvtest
2. Press `Set true` or `Set string` or `Set 1` button
3. Press `Set false` or `Set empty string` or `Set 0` button
4. See warning `Trying to set a null value to hook for type (boolean | string | number) is not allowed`, values ain't changed

**Expected behavior**
Result text should show `False`, blank, `0`

**Screenshots**
![Screenshot_20210922-001025](https://user-images.githubusercontent.com/31266357/134216607-82d645c5-f55f-4b26-80b1-47c4f0e717bb.png)

**Platform Information:**
 - OS: Android
 - React Native Version 0.65.1
 - Library Version 0.6.3

**Additional context**
N/A

**Comment by ammarahm-ed** [comment]
I will investigate this

**Comment by ammarahm-ed** [comment]
Fixed it on master. try with:

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```

**Comment by pnthach95** [comment]
I tried, bug isn't fixed. I try set 0, empty string, it shows same warning, pull my test case for new cases. And check my PR #164.

**Comment by ammarahm-ed** [comment]
@pnthach95 Thanks for the fix. I actually did make those changes but forgot to commit which is why it didn't work for you. I have merged now.
